// -------------------------------------------------------------
// 
// File Name: hdlsrc\RNN_Node\RNN_Node.v
// Created: 2021-06-10 13:03:14
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.2
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// y_t                           ce_out        0.2
// h_t                           ce_out        0.2
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RNN_Node
// Source Path: RNN_Node
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RNN_Node
          (clk,
           reset,
           clk_enable,
           W,
           h_t_1,
           U,
           x_t,
           V,
           ce_out,
           y_t,
           h_t);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [31:0] W;  // single
  input   [31:0] h_t_1;  // single
  input   [31:0] U;  // single
  input   [31:0] x_t;  // single
  input   [31:0] V;  // single
  output  ce_out;
  output  [31:0] y_t;  // single
  output  [31:0] h_t;  // single


  wire enb;
  reg [31:0] Delay1_out1;  // ufix32
  reg [31:0] Delay2_out1;  // ufix32
  wire [31:0] Product_out1;  // ufix32
  reg [31:0] Delay3_out1;  // ufix32
  reg [31:0] Delay4_out1;  // ufix32
  wire [31:0] Product1_out1;  // ufix32
  wire [31:0] Add_out1;  // ufix32
  wire [31:0] Tanh_out1;  // ufix32
  reg [31:0] delayMatch_reg [0:62];  // ufix32 [63]
  wire [31:0] delayMatch_reg_next [0:62];  // ufix32 [63]
  wire [31:0] Delay5_out1;  // ufix32
  wire [31:0] Add1_out1;  // ufix32
  reg [31:0] delayMatch1_reg [0:10];  // ufix32 [11]
  wire [31:0] delayMatch1_reg_next [0:10];  // ufix32 [11]
  wire [31:0] Tanh_out1_1;  // ufix32


  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= W;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= h_t_1;
        end
      end
    end



  nfp_mul_single u_nfp_mul_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(clk_enable),
                                 .nfp_in1(Delay1_out1),  // single
                                 .nfp_in2(Delay2_out1),  // single
                                 .nfp_out(Product_out1)  // single
                                 );

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= U;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= x_t;
        end
      end
    end



  nfp_mul_single u_nfp_mul_comp_1 (.clk(clk),
                                   .reset(reset),
                                   .enb(clk_enable),
                                   .nfp_in1(Delay3_out1),  // single
                                   .nfp_in2(Delay4_out1),  // single
                                   .nfp_out(Product1_out1)  // single
                                   );

  nfp_add_single u_nfp_add_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(clk_enable),
                                 .nfp_in1(Product_out1),  // single
                                 .nfp_in2(Product1_out1),  // single
                                 .nfp_out(Add_out1)  // single
                                 );

  nfp_tanh_single u_nfp_tanh_comp (.clk(clk),
                                   .reset(reset),
                                   .enb(clk_enable),
                                   .nfp_in(Add_out1),  // single
                                   .nfp_out(Tanh_out1)  // single
                                   );

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 32'h00000000;
        delayMatch_reg[1] <= 32'h00000000;
        delayMatch_reg[2] <= 32'h00000000;
        delayMatch_reg[3] <= 32'h00000000;
        delayMatch_reg[4] <= 32'h00000000;
        delayMatch_reg[5] <= 32'h00000000;
        delayMatch_reg[6] <= 32'h00000000;
        delayMatch_reg[7] <= 32'h00000000;
        delayMatch_reg[8] <= 32'h00000000;
        delayMatch_reg[9] <= 32'h00000000;
        delayMatch_reg[10] <= 32'h00000000;
        delayMatch_reg[11] <= 32'h00000000;
        delayMatch_reg[12] <= 32'h00000000;
        delayMatch_reg[13] <= 32'h00000000;
        delayMatch_reg[14] <= 32'h00000000;
        delayMatch_reg[15] <= 32'h00000000;
        delayMatch_reg[16] <= 32'h00000000;
        delayMatch_reg[17] <= 32'h00000000;
        delayMatch_reg[18] <= 32'h00000000;
        delayMatch_reg[19] <= 32'h00000000;
        delayMatch_reg[20] <= 32'h00000000;
        delayMatch_reg[21] <= 32'h00000000;
        delayMatch_reg[22] <= 32'h00000000;
        delayMatch_reg[23] <= 32'h00000000;
        delayMatch_reg[24] <= 32'h00000000;
        delayMatch_reg[25] <= 32'h00000000;
        delayMatch_reg[26] <= 32'h00000000;
        delayMatch_reg[27] <= 32'h00000000;
        delayMatch_reg[28] <= 32'h00000000;
        delayMatch_reg[29] <= 32'h00000000;
        delayMatch_reg[30] <= 32'h00000000;
        delayMatch_reg[31] <= 32'h00000000;
        delayMatch_reg[32] <= 32'h00000000;
        delayMatch_reg[33] <= 32'h00000000;
        delayMatch_reg[34] <= 32'h00000000;
        delayMatch_reg[35] <= 32'h00000000;
        delayMatch_reg[36] <= 32'h00000000;
        delayMatch_reg[37] <= 32'h00000000;
        delayMatch_reg[38] <= 32'h00000000;
        delayMatch_reg[39] <= 32'h00000000;
        delayMatch_reg[40] <= 32'h00000000;
        delayMatch_reg[41] <= 32'h00000000;
        delayMatch_reg[42] <= 32'h00000000;
        delayMatch_reg[43] <= 32'h00000000;
        delayMatch_reg[44] <= 32'h00000000;
        delayMatch_reg[45] <= 32'h00000000;
        delayMatch_reg[46] <= 32'h00000000;
        delayMatch_reg[47] <= 32'h00000000;
        delayMatch_reg[48] <= 32'h00000000;
        delayMatch_reg[49] <= 32'h00000000;
        delayMatch_reg[50] <= 32'h00000000;
        delayMatch_reg[51] <= 32'h00000000;
        delayMatch_reg[52] <= 32'h00000000;
        delayMatch_reg[53] <= 32'h00000000;
        delayMatch_reg[54] <= 32'h00000000;
        delayMatch_reg[55] <= 32'h00000000;
        delayMatch_reg[56] <= 32'h00000000;
        delayMatch_reg[57] <= 32'h00000000;
        delayMatch_reg[58] <= 32'h00000000;
        delayMatch_reg[59] <= 32'h00000000;
        delayMatch_reg[60] <= 32'h00000000;
        delayMatch_reg[61] <= 32'h00000000;
        delayMatch_reg[62] <= 32'h00000000;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
          delayMatch_reg[2] <= delayMatch_reg_next[2];
          delayMatch_reg[3] <= delayMatch_reg_next[3];
          delayMatch_reg[4] <= delayMatch_reg_next[4];
          delayMatch_reg[5] <= delayMatch_reg_next[5];
          delayMatch_reg[6] <= delayMatch_reg_next[6];
          delayMatch_reg[7] <= delayMatch_reg_next[7];
          delayMatch_reg[8] <= delayMatch_reg_next[8];
          delayMatch_reg[9] <= delayMatch_reg_next[9];
          delayMatch_reg[10] <= delayMatch_reg_next[10];
          delayMatch_reg[11] <= delayMatch_reg_next[11];
          delayMatch_reg[12] <= delayMatch_reg_next[12];
          delayMatch_reg[13] <= delayMatch_reg_next[13];
          delayMatch_reg[14] <= delayMatch_reg_next[14];
          delayMatch_reg[15] <= delayMatch_reg_next[15];
          delayMatch_reg[16] <= delayMatch_reg_next[16];
          delayMatch_reg[17] <= delayMatch_reg_next[17];
          delayMatch_reg[18] <= delayMatch_reg_next[18];
          delayMatch_reg[19] <= delayMatch_reg_next[19];
          delayMatch_reg[20] <= delayMatch_reg_next[20];
          delayMatch_reg[21] <= delayMatch_reg_next[21];
          delayMatch_reg[22] <= delayMatch_reg_next[22];
          delayMatch_reg[23] <= delayMatch_reg_next[23];
          delayMatch_reg[24] <= delayMatch_reg_next[24];
          delayMatch_reg[25] <= delayMatch_reg_next[25];
          delayMatch_reg[26] <= delayMatch_reg_next[26];
          delayMatch_reg[27] <= delayMatch_reg_next[27];
          delayMatch_reg[28] <= delayMatch_reg_next[28];
          delayMatch_reg[29] <= delayMatch_reg_next[29];
          delayMatch_reg[30] <= delayMatch_reg_next[30];
          delayMatch_reg[31] <= delayMatch_reg_next[31];
          delayMatch_reg[32] <= delayMatch_reg_next[32];
          delayMatch_reg[33] <= delayMatch_reg_next[33];
          delayMatch_reg[34] <= delayMatch_reg_next[34];
          delayMatch_reg[35] <= delayMatch_reg_next[35];
          delayMatch_reg[36] <= delayMatch_reg_next[36];
          delayMatch_reg[37] <= delayMatch_reg_next[37];
          delayMatch_reg[38] <= delayMatch_reg_next[38];
          delayMatch_reg[39] <= delayMatch_reg_next[39];
          delayMatch_reg[40] <= delayMatch_reg_next[40];
          delayMatch_reg[41] <= delayMatch_reg_next[41];
          delayMatch_reg[42] <= delayMatch_reg_next[42];
          delayMatch_reg[43] <= delayMatch_reg_next[43];
          delayMatch_reg[44] <= delayMatch_reg_next[44];
          delayMatch_reg[45] <= delayMatch_reg_next[45];
          delayMatch_reg[46] <= delayMatch_reg_next[46];
          delayMatch_reg[47] <= delayMatch_reg_next[47];
          delayMatch_reg[48] <= delayMatch_reg_next[48];
          delayMatch_reg[49] <= delayMatch_reg_next[49];
          delayMatch_reg[50] <= delayMatch_reg_next[50];
          delayMatch_reg[51] <= delayMatch_reg_next[51];
          delayMatch_reg[52] <= delayMatch_reg_next[52];
          delayMatch_reg[53] <= delayMatch_reg_next[53];
          delayMatch_reg[54] <= delayMatch_reg_next[54];
          delayMatch_reg[55] <= delayMatch_reg_next[55];
          delayMatch_reg[56] <= delayMatch_reg_next[56];
          delayMatch_reg[57] <= delayMatch_reg_next[57];
          delayMatch_reg[58] <= delayMatch_reg_next[58];
          delayMatch_reg[59] <= delayMatch_reg_next[59];
          delayMatch_reg[60] <= delayMatch_reg_next[60];
          delayMatch_reg[61] <= delayMatch_reg_next[61];
          delayMatch_reg[62] <= delayMatch_reg_next[62];
        end
      end
    end

  assign Delay5_out1 = delayMatch_reg[62];
  assign delayMatch_reg_next[0] = V;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];
  assign delayMatch_reg_next[2] = delayMatch_reg[1];
  assign delayMatch_reg_next[3] = delayMatch_reg[2];
  assign delayMatch_reg_next[4] = delayMatch_reg[3];
  assign delayMatch_reg_next[5] = delayMatch_reg[4];
  assign delayMatch_reg_next[6] = delayMatch_reg[5];
  assign delayMatch_reg_next[7] = delayMatch_reg[6];
  assign delayMatch_reg_next[8] = delayMatch_reg[7];
  assign delayMatch_reg_next[9] = delayMatch_reg[8];
  assign delayMatch_reg_next[10] = delayMatch_reg[9];
  assign delayMatch_reg_next[11] = delayMatch_reg[10];
  assign delayMatch_reg_next[12] = delayMatch_reg[11];
  assign delayMatch_reg_next[13] = delayMatch_reg[12];
  assign delayMatch_reg_next[14] = delayMatch_reg[13];
  assign delayMatch_reg_next[15] = delayMatch_reg[14];
  assign delayMatch_reg_next[16] = delayMatch_reg[15];
  assign delayMatch_reg_next[17] = delayMatch_reg[16];
  assign delayMatch_reg_next[18] = delayMatch_reg[17];
  assign delayMatch_reg_next[19] = delayMatch_reg[18];
  assign delayMatch_reg_next[20] = delayMatch_reg[19];
  assign delayMatch_reg_next[21] = delayMatch_reg[20];
  assign delayMatch_reg_next[22] = delayMatch_reg[21];
  assign delayMatch_reg_next[23] = delayMatch_reg[22];
  assign delayMatch_reg_next[24] = delayMatch_reg[23];
  assign delayMatch_reg_next[25] = delayMatch_reg[24];
  assign delayMatch_reg_next[26] = delayMatch_reg[25];
  assign delayMatch_reg_next[27] = delayMatch_reg[26];
  assign delayMatch_reg_next[28] = delayMatch_reg[27];
  assign delayMatch_reg_next[29] = delayMatch_reg[28];
  assign delayMatch_reg_next[30] = delayMatch_reg[29];
  assign delayMatch_reg_next[31] = delayMatch_reg[30];
  assign delayMatch_reg_next[32] = delayMatch_reg[31];
  assign delayMatch_reg_next[33] = delayMatch_reg[32];
  assign delayMatch_reg_next[34] = delayMatch_reg[33];
  assign delayMatch_reg_next[35] = delayMatch_reg[34];
  assign delayMatch_reg_next[36] = delayMatch_reg[35];
  assign delayMatch_reg_next[37] = delayMatch_reg[36];
  assign delayMatch_reg_next[38] = delayMatch_reg[37];
  assign delayMatch_reg_next[39] = delayMatch_reg[38];
  assign delayMatch_reg_next[40] = delayMatch_reg[39];
  assign delayMatch_reg_next[41] = delayMatch_reg[40];
  assign delayMatch_reg_next[42] = delayMatch_reg[41];
  assign delayMatch_reg_next[43] = delayMatch_reg[42];
  assign delayMatch_reg_next[44] = delayMatch_reg[43];
  assign delayMatch_reg_next[45] = delayMatch_reg[44];
  assign delayMatch_reg_next[46] = delayMatch_reg[45];
  assign delayMatch_reg_next[47] = delayMatch_reg[46];
  assign delayMatch_reg_next[48] = delayMatch_reg[47];
  assign delayMatch_reg_next[49] = delayMatch_reg[48];
  assign delayMatch_reg_next[50] = delayMatch_reg[49];
  assign delayMatch_reg_next[51] = delayMatch_reg[50];
  assign delayMatch_reg_next[52] = delayMatch_reg[51];
  assign delayMatch_reg_next[53] = delayMatch_reg[52];
  assign delayMatch_reg_next[54] = delayMatch_reg[53];
  assign delayMatch_reg_next[55] = delayMatch_reg[54];
  assign delayMatch_reg_next[56] = delayMatch_reg[55];
  assign delayMatch_reg_next[57] = delayMatch_reg[56];
  assign delayMatch_reg_next[58] = delayMatch_reg[57];
  assign delayMatch_reg_next[59] = delayMatch_reg[58];
  assign delayMatch_reg_next[60] = delayMatch_reg[59];
  assign delayMatch_reg_next[61] = delayMatch_reg[60];
  assign delayMatch_reg_next[62] = delayMatch_reg[61];



  nfp_add_single u_nfp_add_comp_1 (.clk(clk),
                                   .reset(reset),
                                   .enb(clk_enable),
                                   .nfp_in1(Tanh_out1),  // single
                                   .nfp_in2(Delay5_out1),  // single
                                   .nfp_out(Add1_out1)  // single
                                   );

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg[0] <= 32'h00000000;
        delayMatch1_reg[1] <= 32'h00000000;
        delayMatch1_reg[2] <= 32'h00000000;
        delayMatch1_reg[3] <= 32'h00000000;
        delayMatch1_reg[4] <= 32'h00000000;
        delayMatch1_reg[5] <= 32'h00000000;
        delayMatch1_reg[6] <= 32'h00000000;
        delayMatch1_reg[7] <= 32'h00000000;
        delayMatch1_reg[8] <= 32'h00000000;
        delayMatch1_reg[9] <= 32'h00000000;
        delayMatch1_reg[10] <= 32'h00000000;
      end
      else begin
        if (enb) begin
          delayMatch1_reg[0] <= delayMatch1_reg_next[0];
          delayMatch1_reg[1] <= delayMatch1_reg_next[1];
          delayMatch1_reg[2] <= delayMatch1_reg_next[2];
          delayMatch1_reg[3] <= delayMatch1_reg_next[3];
          delayMatch1_reg[4] <= delayMatch1_reg_next[4];
          delayMatch1_reg[5] <= delayMatch1_reg_next[5];
          delayMatch1_reg[6] <= delayMatch1_reg_next[6];
          delayMatch1_reg[7] <= delayMatch1_reg_next[7];
          delayMatch1_reg[8] <= delayMatch1_reg_next[8];
          delayMatch1_reg[9] <= delayMatch1_reg_next[9];
          delayMatch1_reg[10] <= delayMatch1_reg_next[10];
        end
      end
    end

  assign Tanh_out1_1 = delayMatch1_reg[10];
  assign delayMatch1_reg_next[0] = Tanh_out1;
  assign delayMatch1_reg_next[1] = delayMatch1_reg[0];
  assign delayMatch1_reg_next[2] = delayMatch1_reg[1];
  assign delayMatch1_reg_next[3] = delayMatch1_reg[2];
  assign delayMatch1_reg_next[4] = delayMatch1_reg[3];
  assign delayMatch1_reg_next[5] = delayMatch1_reg[4];
  assign delayMatch1_reg_next[6] = delayMatch1_reg[5];
  assign delayMatch1_reg_next[7] = delayMatch1_reg[6];
  assign delayMatch1_reg_next[8] = delayMatch1_reg[7];
  assign delayMatch1_reg_next[9] = delayMatch1_reg[8];
  assign delayMatch1_reg_next[10] = delayMatch1_reg[9];



  assign ce_out = clk_enable;

  assign y_t = Add1_out1;

  assign h_t = Tanh_out1_1;

endmodule  // RNN_Node

